/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUParametrosFlujoFondos.java
 *
 * Created on 29-dic-2010, 11:57:28
 */

package viviendas.gui.flujoFondos;

import javax.swing.InputVerifier;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import viviendas.utiles.Utiles;

/**
 *
 * @author Maximiliano.
 */
public class IUParametrosFlujoFondos extends javax.swing.JInternalFrame {
    
    public IUParametrosFlujoFondos() {
        initComponents();
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JTextField getTxtComsionOtorgamiento() {
        return txtComsionOtorgamiento;
    }

    public JTextField getTxtGastosAdministrativos() {
        return txtGastosAdministrativos;
    }

    public JTextField getTxtMomentoOtorg() {
        return txtMomentoOtorg;
    }

    public JTextField getTxtPlazoGracia() {
        return txtPlazoGracia;
    }

    public JTextField getTxtTNA() {
        return txtTNA;
    }

    public JComboBox getCmbCiudades() {
        return cmbCiudades;
    }

    public JComboBox getCmbOperatorias() {
        return cmbOperatorias;
    }

    public JComboBox getCmbProvincias() {
        return cmbProvincias;
    }

    public JComboBox getCmbSectorEconomico() {
        return cmbSectorEconomico;
    }

    public JComboBox getCmbPlan() {
        return cmbPlan;
    }
   
    public JInternalFrame getPantalla(){
        return this;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelDevolCred = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGastosAdministrativos = new javax.swing.JTextField();
        txtTNA = new javax.swing.JTextField();
        txtComsionOtorgamiento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMomentoOtorg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPlazoGracia = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbProvincias = new javax.swing.JComboBox();
        cmbCiudades = new javax.swing.JComboBox();
        cmbSectorEconomico = new javax.swing.JComboBox();
        cmbOperatorias = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cmbPlan = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Flujo de Fondos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Home.png"))); // NOI18N

        panelDevolCred.setBackground(new java.awt.Color(204, 204, 204));
        panelDevolCred.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros"));
        panelDevolCred.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("% de Interes (TNA)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelDevolCred.add(jLabel1, gridBagConstraints);

        txtGastosAdministrativos.setMinimumSize(new java.awt.Dimension(50, 20));
        txtGastosAdministrativos.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        panelDevolCred.add(txtGastosAdministrativos, gridBagConstraints);
        txtGastosAdministrativos.setInputVerifier(new InputVerifier()
            {
                public boolean verify(JComponent input) {
                    JTextField tf = (JTextField) input;
                    String cadena = tf.getText();

                    if(!Utiles.validarStringNumericoDouble(cadena)){
                        JOptionPane.showMessageDialog(getPantalla(), "Solo se permiten valores numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
                        return false;
                    }
                    return true;
                }
            });

            txtTNA.setPreferredSize(new java.awt.Dimension(50, 20));
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
            gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
            panelDevolCred.add(txtTNA, gridBagConstraints);
            txtTNA.setInputVerifier(new InputVerifier()
                {
                    public boolean verify(JComponent input) {
                        JTextField tf = (JTextField) input;
                        String cadena = tf.getText();

                        if(!Utiles.validarStringNumericoDouble(cadena)){
                            JOptionPane.showMessageDialog(getPantalla(), "Solo se permiten valores numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
                            return false;
                        }
                        return true;
                    }
                });

                txtComsionOtorgamiento.setMinimumSize(new java.awt.Dimension(50, 20));
                txtComsionOtorgamiento.setPreferredSize(new java.awt.Dimension(50, 20));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
                panelDevolCred.add(txtComsionOtorgamiento, gridBagConstraints);
                txtComsionOtorgamiento.setInputVerifier(new InputVerifier()
                    {
                        public boolean verify(JComponent input) {
                            JTextField tf = (JTextField) input;
                            String cadena = tf.getText();

                            if(!Utiles.validarStringNumericoDouble(cadena)){
                                JOptionPane.showMessageDialog(getPantalla(), "Solo se permiten valores numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
                                return false;
                            }
                            return true;
                        }
                    });

                    jLabel2.setText("Comisión de Otorgamiento");
                    gridBagConstraints = new java.awt.GridBagConstraints();
                    gridBagConstraints.gridx = 0;
                    gridBagConstraints.gridy = 1;
                    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                    panelDevolCred.add(jLabel2, gridBagConstraints);

                    jLabel3.setText("Gastos Administrativos");
                    gridBagConstraints = new java.awt.GridBagConstraints();
                    gridBagConstraints.gridx = 0;
                    gridBagConstraints.gridy = 2;
                    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                    panelDevolCred.add(jLabel3, gridBagConstraints);

                    jLabel9.setText("Momento Otorgamiento");
                    gridBagConstraints = new java.awt.GridBagConstraints();
                    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                    panelDevolCred.add(jLabel9, gridBagConstraints);

                    txtMomentoOtorg.setMinimumSize(new java.awt.Dimension(50, 20));
                    txtMomentoOtorg.setPreferredSize(new java.awt.Dimension(50, 20));
                    gridBagConstraints = new java.awt.GridBagConstraints();
                    gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
                    panelDevolCred.add(txtMomentoOtorg, gridBagConstraints);
                    txtMomentoOtorg.setInputVerifier(new InputVerifier()
                        {
                            public boolean verify(JComponent input) {
                                JTextField tf = (JTextField) input;
                                String cadena = tf.getText();

                                if(!Utiles.validarStringNumericoDouble(cadena)){
                                    JOptionPane.showMessageDialog(getPantalla(), "Solo se permiten valores numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
                                    return false;
                                }
                                return true;
                            }
                        });

                        jLabel10.setText("Plazo Gracia");
                        gridBagConstraints = new java.awt.GridBagConstraints();
                        gridBagConstraints.gridx = 2;
                        gridBagConstraints.gridy = 1;
                        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                        panelDevolCred.add(jLabel10, gridBagConstraints);

                        txtPlazoGracia.setMinimumSize(new java.awt.Dimension(50, 20));
                        txtPlazoGracia.setPreferredSize(new java.awt.Dimension(50, 20));
                        gridBagConstraints = new java.awt.GridBagConstraints();
                        gridBagConstraints.gridx = 3;
                        gridBagConstraints.gridy = 1;
                        gridBagConstraints.insets = new java.awt.Insets(6, 8, 6, 8);
                        panelDevolCred.add(txtPlazoGracia, gridBagConstraints);
                        txtPlazoGracia.setInputVerifier(new InputVerifier()
                            {
                                public boolean verify(JComponent input) {
                                    JTextField tf = (JTextField) input;
                                    String cadena = tf.getText();

                                    if(!Utiles.validarStringNumericoDouble(cadena)){
                                        JOptionPane.showMessageDialog(getPantalla(), "Solo se permiten valores numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
                                        return false;
                                    }
                                    return true;
                                }
                            });

                            btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Save.png"))); // NOI18N
                            btnAceptar.setText("Guardar");

                            btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Delete.png"))); // NOI18N
                            btnCancelar.setText("Cancelar");

                            jPanel1.setBackground(new java.awt.Color(153, 153, 153));
                            jPanel1.setLayout(new java.awt.GridBagLayout());

                            jLabel4.setText("Provincias");
                            gridBagConstraints = new java.awt.GridBagConstraints();
                            gridBagConstraints.gridx = 0;
                            gridBagConstraints.gridy = 2;
                            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                            gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                            gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
                            jPanel1.add(jLabel4, gridBagConstraints);

                            jLabel5.setText("Ciudades");
                            gridBagConstraints = new java.awt.GridBagConstraints();
                            gridBagConstraints.gridx = 0;
                            gridBagConstraints.gridy = 4;
                            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                            gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                            gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
                            jPanel1.add(jLabel5, gridBagConstraints);

                            jLabel6.setText("Seg. Econom.");
                            gridBagConstraints = new java.awt.GridBagConstraints();
                            gridBagConstraints.gridx = 0;
                            gridBagConstraints.gridy = 6;
                            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                            gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                            gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
                            jPanel1.add(jLabel6, gridBagConstraints);

                            jLabel7.setText("Operatorias");
                            gridBagConstraints = new java.awt.GridBagConstraints();
                            gridBagConstraints.gridx = 0;
                            gridBagConstraints.gridy = 8;
                            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                            gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                            gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
                            jPanel1.add(jLabel7, gridBagConstraints);

                            cmbProvincias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                            gridBagConstraints = new java.awt.GridBagConstraints();
                            gridBagConstraints.gridx = 1;
                            gridBagConstraints.gridy = 2;
                            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                            gridBagConstraints.ipadx = 100;
                            jPanel1.add(cmbProvincias, gridBagConstraints);

                            cmbCiudades.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                            gridBagConstraints = new java.awt.GridBagConstraints();
                            gridBagConstraints.gridx = 1;
                            gridBagConstraints.gridy = 4;
                            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                            jPanel1.add(cmbCiudades, gridBagConstraints);

                            cmbSectorEconomico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                            gridBagConstraints = new java.awt.GridBagConstraints();
                            gridBagConstraints.gridx = 1;
                            gridBagConstraints.gridy = 6;
                            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                            jPanel1.add(cmbSectorEconomico, gridBagConstraints);

                            cmbOperatorias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                            gridBagConstraints = new java.awt.GridBagConstraints();
                            gridBagConstraints.gridx = 1;
                            gridBagConstraints.gridy = 8;
                            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                            jPanel1.add(cmbOperatorias, gridBagConstraints);

                            jLabel8.setText("Plan");
                            gridBagConstraints = new java.awt.GridBagConstraints();
                            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                            gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
                            jPanel1.add(jLabel8, gridBagConstraints);

                            cmbPlan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                            gridBagConstraints = new java.awt.GridBagConstraints();
                            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                            jPanel1.add(cmbPlan, gridBagConstraints);

                            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                            getContentPane().setLayout(layout);
                            layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(188, 188, 188)
                                            .addComponent(btnAceptar)
                                            .addGap(87, 87, 87)
                                            .addComponent(btnCancelar))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(140, 140, 140)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(panelDevolCred, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addContainerGap(165, Short.MAX_VALUE))
                            );
                            layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(panelDevolCred, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(25, 25, 25))
                            );

                            pack();
                        }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cmbCiudades;
    private javax.swing.JComboBox cmbOperatorias;
    private javax.swing.JComboBox cmbPlan;
    private javax.swing.JComboBox cmbProvincias;
    private javax.swing.JComboBox cmbSectorEconomico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelDevolCred;
    private javax.swing.JTextField txtComsionOtorgamiento;
    private javax.swing.JTextField txtGastosAdministrativos;
    private javax.swing.JTextField txtMomentoOtorg;
    private javax.swing.JTextField txtPlazoGracia;
    private javax.swing.JTextField txtTNA;
    // End of variables declaration//GEN-END:variables

}
