/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUFinanciacion.java
 *
 * Created on 20/12/2010, 13:00:17
 */

package viviendas.gui.financiacion.crear;

import javax.swing.JButton;
import javax.swing.JSpinner;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author batte
 */
public class IUFinanciacion extends javax.swing.JInternalFrame {

    /** Creates new form IUFinanciacion */
    public IUFinanciacion() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labNombre = new javax.swing.JLabel();
        _texNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        _btnOk = new javax.swing.JButton();
        _btnCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        _btnDropDetails = new javax.swing.JButton();
        _btnViewDetails = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        _btnAdd = new javax.swing.JButton();
        _btnDel = new javax.swing.JButton();
        _tabPaneFinanciacion = new javax.swing.JTabbedPane();
        _spinPorcentaje = new javax.swing.JSpinner();
        labPorcentaje = new javax.swing.JLabel();
        _btnCrearFinanciacion = new javax.swing.JButton();
        _texRestante = new javax.swing.JTextField();
        _texTotal = new javax.swing.JTextField();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Home.png"))); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        getContentPane().add(labNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 10, 15);
        getContentPane().add(_texNombre, gridBagConstraints);

        jLabel2.setText("MENDOZA - 20.000 - BAJO - COOPERATIVA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        getContentPane().add(jLabel2, gridBagConstraints);

        jToolBar1.setRollover(true);

        _btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Save.png"))); // NOI18N
        _btnOk.setEnabled(false);
        jToolBar1.add(_btnOk);

        _btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Log Out_16x16.png"))); // NOI18N
        jToolBar1.add(_btnCancel);
        jToolBar1.add(jSeparator1);

        _btnDropDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Previous_16x16.png"))); // NOI18N
        _btnDropDetails.setEnabled(false);
        jToolBar1.add(_btnDropDetails);

        _btnViewDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Next_16x16.png"))); // NOI18N
        _btnViewDetails.setEnabled(false);
        jToolBar1.add(_btnViewDetails);
        jToolBar1.add(jSeparator2);

        _btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/+.png"))); // NOI18N
        _btnAdd.setFocusable(false);
        _btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(_btnAdd);

        _btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/-.png"))); // NOI18N
        _btnDel.setEnabled(false);
        _btnDel.setFocusable(false);
        _btnDel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _btnDel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(_btnDel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        getContentPane().add(jToolBar1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        getContentPane().add(_tabPaneFinanciacion, gridBagConstraints);

        _spinPorcentaje.setModel(new javax.swing.SpinnerNumberModel(100.0d, 0.0d, 100.0d, 0.10000000000000009d));
        _spinPorcentaje.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 10, 15);
        getContentPane().add(_spinPorcentaje, gridBagConstraints);

        labPorcentaje.setText("Porcentaje: ");
        labPorcentaje.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        getContentPane().add(labPorcentaje, gridBagConstraints);

        _btnCrearFinanciacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Accept.png"))); // NOI18N
        _btnCrearFinanciacion.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 10, 15);
        getContentPane().add(_btnCrearFinanciacion, gridBagConstraints);

        _texRestante.setEditable(false);
        _texRestante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Restante", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        _texRestante.setMinimumSize(new java.awt.Dimension(88, 44));
        _texRestante.setPreferredSize(new java.awt.Dimension(88, 44));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        getContentPane().add(_texRestante, gridBagConstraints);

        _texTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        _texTotal.setMinimumSize(new java.awt.Dimension(88, 44));
        _texTotal.setPreferredSize(new java.awt.Dimension(88, 44));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 10, 15);
        getContentPane().add(_texTotal, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnAdd;
    private javax.swing.JButton _btnCancel;
    private javax.swing.JButton _btnCrearFinanciacion;
    private javax.swing.JButton _btnDel;
    private javax.swing.JButton _btnDropDetails;
    private javax.swing.JButton _btnOk;
    private javax.swing.JButton _btnViewDetails;
    private javax.swing.JSpinner _spinPorcentaje;
    private javax.swing.JTabbedPane _tabPaneFinanciacion;
    private javax.swing.JTextField _texNombre;
    private javax.swing.JTextField _texRestante;
    private javax.swing.JTextField _texTotal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labNombre;
    private javax.swing.JLabel labPorcentaje;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAdd() {
        return _btnAdd;
    }

    public void setBtnAdd(JButton _btnAdd) {
        this._btnAdd = _btnAdd;
    }

    public JButton getBtnCancel() {
        return _btnCancel;
    }

    public void setBtnCancel(JButton _btnCancel) {
        this._btnCancel = _btnCancel;
    }

    public JButton getBtnCrearFinanciacion() {
        return _btnCrearFinanciacion;
    }

    public void setBtnCrearFinanciacion(JButton _btnCrearFinanciacion) {
        this._btnCrearFinanciacion = _btnCrearFinanciacion;
    }

    public JButton getBtnDel() {
        return _btnDel;
    }

    public void setBtnDel(JButton _btnDel) {
        this._btnDel = _btnDel;
    }

    public JButton getBtnDropDetails() {
        return _btnDropDetails;
    }

    public void setBtnDropDetails(JButton _btnDropDetails) {
        this._btnDropDetails = _btnDropDetails;
    }

    public JButton getBtnOk() {
        return _btnOk;
    }

    public void setBtnOk(JButton _btnOk) {
        this._btnOk = _btnOk;
    }

    public JButton getBtnViewDetails() {
        return _btnViewDetails;
    }

    public void setBtnViewDetails(JButton _btnViewDetails) {
        this._btnViewDetails = _btnViewDetails;
    }

    public JTabbedPane getTabPaneFinanciacion() {
        return _tabPaneFinanciacion;
    }

    public void setTabPaneFinanciacion(JTabbedPane _tabPaneFinanciacion) {
        this._tabPaneFinanciacion = _tabPaneFinanciacion;
    }

    public JTextField getTexNombre() {
        return _texNombre;
    }

    public void setTexNombre(JTextField _texNombre) {
        this._texNombre = _texNombre;
    }

    public JSpinner getSpinPorcentaje() {
        return _spinPorcentaje;
    }

    public void setSpinPorcentaje(JSpinner _spinPorcentaje) {
        this._spinPorcentaje = _spinPorcentaje;
    }

    public JTextField getTexRestante() {
        return _texRestante;
    }

    public void setTexRestante(JTextField _texRestante) {
        this._texRestante = _texRestante;
    }

    public JTextField getTexTotal() {
        return _texTotal;
    }

    public void setTexTotal(JTextField _texTotal) {
        this._texTotal = _texTotal;
    }
}
