/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUModificarPlan.java
 *
 * Created on 09/12/2010, 10:48:38
 */

package viviendas.gui.Plan.modificar;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author desarrollo
 */
public class IUModificarPlanNew extends javax.swing.JInternalFrame {

    /** Creates new form IUModificarPlan */
    public IUModificarPlanNew() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        _txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        _txtTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        _txtTotViviendas = new javax.swing.JTextField();
        _txtAños = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        _btnViewDetails = new javax.swing.JButton();
        _btnDropDetails = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        _btnAdd = new javax.swing.JButton();
        _btnDel = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        _btnOk = new javax.swing.JButton();
        _btnCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        _txtRestante = new javax.swing.JTextField();
        _txtTotal = new javax.swing.JTextField();
        _lblAño = new javax.swing.JLabel();
        _lblProvincia = new javax.swing.JLabel();
        _lblCiudad = new javax.swing.JLabel();
        _lblSector = new javax.swing.JLabel();
        _lblOperatoria = new javax.swing.JLabel();
        _pnlCentral = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        _btnAddFinanciacion = new javax.swing.JButton();
        _btnPlan = new javax.swing.JButton();
        _btnInversion = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Modificar Plan");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Home.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos Plan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.gray)); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jLabel1, gridBagConstraints);

        _txtNombre.setEditable(false);
        _txtNombre.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(_txtNombre, gridBagConstraints);

        jLabel2.setText("Tipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jLabel2, gridBagConstraints);

        _txtTipo.setEditable(false);
        _txtTipo.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(_txtTipo, gridBagConstraints);

        jLabel3.setText("Años");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Total Viviendas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jLabel4, gridBagConstraints);

        _txtTotViviendas.setEditable(false);
        _txtTotViviendas.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(_txtTotViviendas, gridBagConstraints);

        _txtAños.setEditable(false);
        _txtAños.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        _txtAños.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(_txtAños, gridBagConstraints);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        _btnViewDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Next_16x16.png"))); // NOI18N
        jToolBar1.add(_btnViewDetails);

        _btnDropDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Previous_16x16.png"))); // NOI18N
        _btnDropDetails.setEnabled(false);
        jToolBar1.add(_btnDropDetails);
        jToolBar1.add(jSeparator2);

        _btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/+.png"))); // NOI18N
        _btnAdd.setFocusable(false);
        _btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(_btnAdd);

        _btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/-.png"))); // NOI18N
        _btnDel.setFocusable(false);
        _btnDel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _btnDel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(_btnDel);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator1);

        _btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Save.png"))); // NOI18N
        jToolBar1.add(_btnOk);

        _btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Log Out_16x16.png"))); // NOI18N
        jToolBar1.add(_btnCancel);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        _txtRestante.setEditable(false);
        _txtRestante.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        _txtRestante.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _txtRestante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "% Restante", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        _txtTotal.setEditable(false);
        _txtTotal.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        _txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _txtTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "% Total", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        _lblAño.setBorder(null);

        _lblProvincia.setBorder(null);

        _lblCiudad.setBorder(null);

        _lblSector.setBorder(null);

        _lblOperatoria.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(_txtRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(_txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(_lblAño, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_lblProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_lblCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(_lblSector, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(_lblOperatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_txtRestante)
                    .addComponent(_txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_lblOperatoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(_lblSector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(_lblProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(_lblCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(_lblAño, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
        );

        _pnlCentral.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout _pnlCentralLayout = new javax.swing.GroupLayout(_pnlCentral);
        _pnlCentral.setLayout(_pnlCentralLayout);
        _pnlCentralLayout.setHorizontalGroup(
            _pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        _pnlCentralLayout.setVerticalGroup(
            _pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        _btnAddFinanciacion.setText("Financiacion");
        _btnAddFinanciacion.setBorderPainted(false);
        _btnAddFinanciacion.setFocusable(false);
        _btnAddFinanciacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        _btnAddFinanciacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _btnAddFinanciacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        _btnPlan.setText("Plan");
        _btnPlan.setBorderPainted(false);
        _btnPlan.setFocusable(false);
        _btnPlan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        _btnPlan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _btnPlan.setSelected(true);
        _btnPlan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        _btnInversion.setText("Inversion");
        _btnInversion.setBorderPainted(false);
        _btnInversion.setFocusable(false);
        _btnInversion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        _btnInversion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        _btnInversion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_btnPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addComponent(_btnAddFinanciacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_btnInversion, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(_btnPlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_btnAddFinanciacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_btnInversion)
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                            .addComponent(_pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnAdd;
    private javax.swing.JButton _btnAddFinanciacion;
    private javax.swing.JButton _btnCancel;
    private javax.swing.JButton _btnDel;
    private javax.swing.JButton _btnDropDetails;
    private javax.swing.JButton _btnInversion;
    private javax.swing.JButton _btnOk;
    private javax.swing.JButton _btnPlan;
    private javax.swing.JButton _btnViewDetails;
    private javax.swing.JLabel _lblAño;
    private javax.swing.JLabel _lblCiudad;
    private javax.swing.JLabel _lblOperatoria;
    private javax.swing.JLabel _lblProvincia;
    private javax.swing.JLabel _lblSector;
    private javax.swing.JPanel _pnlCentral;
    private javax.swing.JTextField _txtAños;
    private javax.swing.JTextField _txtNombre;
    private javax.swing.JTextField _txtRestante;
    private javax.swing.JTextField _txtTipo;
    private javax.swing.JTextField _txtTotViviendas;
    private javax.swing.JTextField _txtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCancel() {
        return _btnCancel;
    }

    public JButton getBtnOk() {
        return _btnOk;
    }

    public JTextField getTxtNombre() {
        return _txtNombre;
    }

    public JTextField getTxtTipo() {
        return _txtTipo;
    }

    public JTextField getTxtTotViviendas() {
        return _txtTotViviendas;
    }

    public JButton getBtnDropDetails() {
        return _btnDropDetails;
    }

    public JButton getBtnViewDetails() {
        return _btnViewDetails;
    }

    public JTextField getTxtTotal() {
        return _txtTotal;
    }

    public JTextField getTxtAños() {
        return _txtAños;
    }

    public JTextField getTxtRestante() {
        return _txtRestante;
    }

    public JButton getBtnAdd() {
        return _btnAdd;
    }

    public JButton getBtnDel() {
        return _btnDel;
    }

    public JButton getBtnAddFinanciacion() {
        return _btnAddFinanciacion;
    }

    public JLabel getLblAño() {
        return _lblAño;
    }

    public JLabel getLblCiudad() {
        return _lblCiudad;
    }

    public JLabel getLblOperatoria() {
        return _lblOperatoria;
    }

    public JLabel getLblProvincia() {
        return _lblProvincia;
    }

    public JLabel getLblSector() {
        return _lblSector;
    }

    public JPanel getPnlCentral() {
        return _pnlCentral;
    }

    public void setPnlCentral(JPanel _pnlCentral) {
        this._pnlCentral.add(_pnlCentral);
    }
    public JButton getBtnInversion() {
        return _btnInversion;
    }

    public JButton getBtnPlan() {
        return _btnPlan;
    }

}
