package viviendas.gui.Plan.crear;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

public class IUPlan extends javax.swing.JInternalFrame {

    /** Creates new form IUPlan */
    public IUPlan() {
        initComponents();
        NumberFormat formatoEditar = NumberFormat.getNumberInstance(Locale.US);

        formatoEditar.setGroupingUsed(false); //no me acuerdo para q es esto

        NumberFormatter formateador2 = new NumberFormatter(formatoEditar);
        formateador2.setAllowsInvalid(true);// en false te deja poner sólo nros, yo creo q está bien xq no le vamos a  poner a una entrada algo así como $25.50, así q con eso //yo creo q anda bien, si le pones true, te deja ingresar lo q sea, pero si tenes cargado $10 y editas y le pones "ddd", no te toma eso y te deja en $10, fijate q conviene

        DefaultFormatterFactory fabricaSinPesos = new DefaultFormatterFactory(formateador2, formateador2);

        formatedViviendas.setFormatterFactory(fabricaSinPesos);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        labNombre = new javax.swing.JLabel();
        labTipoPlan = new javax.swing.JLabel();
        labNroViviendasPorAño = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        texNombre = new javax.swing.JTextField();
        comTipoPlan = new javax.swing.JComboBox();
        formatedViviendas = new javax.swing.JFormattedTextField();
        spinAños = new javax.swing.JSpinner();
        texTotalViviendas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProvincias = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnAgregarTodas = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnQuitarTodas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabProvinciasSeleccionadas = new javax.swing.JTable();
        formatedTotal = new javax.swing.JFormattedTextField();
        labTotal = new javax.swing.JLabel();
        labRestante = new javax.swing.JLabel();
        texRestante = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Plan de Vivienda");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paso 1: Especificar Datos del Plan", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        labNombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(labNombre, gridBagConstraints);

        labTipoPlan.setText("Tipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(labTipoPlan, gridBagConstraints);

        labNroViviendasPorAño.setText("Viviendas x Año");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(labNroViviendasPorAño, gridBagConstraints);

        jLabel4.setText("Cantidad Años");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Total Viviendas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel1.add(jLabel5, gridBagConstraints);

        texNombre.setPreferredSize(new java.awt.Dimension(150, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(texNombre, gridBagConstraints);

        comTipoPlan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(comTipoPlan, gridBagConstraints);

        formatedViviendas.setPreferredSize(new java.awt.Dimension(150, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(formatedViviendas, gridBagConstraints);

        spinAños.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)1), Byte.valueOf((byte)1), Byte.valueOf((byte)50), Byte.valueOf((byte)1)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(spinAños, gridBagConstraints);

        texTotalViviendas.setEditable(false);
        texTotalViviendas.setEnabled(false);
        texTotalViviendas.setPreferredSize(new java.awt.Dimension(150, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(texTotalViviendas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paso 2: Agregar Provincias al Plan", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(350, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(350, 200));

        tabProvincias.setMinimumSize(new java.awt.Dimension(350, 200));
        tabProvincias.setPreferredSize(new java.awt.Dimension(350, 200));
        jScrollPane1.setViewportView(tabProvincias);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jScrollPane1, gridBagConstraints);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/+.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 30);
        jPanel3.add(btnAgregar, gridBagConstraints);

        btnAgregarTodas.setText(">>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 30);
        jPanel3.add(btnAgregarTodas, gridBagConstraints);

        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/-.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 30);
        jPanel3.add(btnQuitar, gridBagConstraints);

        btnQuitarTodas.setText("<<");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 30);
        jPanel3.add(btnQuitarTodas, gridBagConstraints);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(350, 200));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(350, 200));

        tabProvinciasSeleccionadas.setMinimumSize(new java.awt.Dimension(350, 200));
        tabProvinciasSeleccionadas.setPreferredSize(new java.awt.Dimension(350, 200));
        jScrollPane2.setViewportView(tabProvinciasSeleccionadas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jScrollPane2, gridBagConstraints);

        formatedTotal.setAutoscrolls(true);
        formatedTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        formatedTotal.setMinimumSize(new java.awt.Dimension(80, 27));
        formatedTotal.setPreferredSize(new java.awt.Dimension(80, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        jPanel3.add(formatedTotal, gridBagConstraints);

        labTotal.setText("% Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        jPanel3.add(labTotal, gridBagConstraints);

        labRestante.setText("% Restante");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        jPanel3.add(labRestante, gridBagConstraints);

        texRestante.setAutoscrolls(true);
        texRestante.setMinimumSize(new java.awt.Dimension(80, 27));
        texRestante.setPreferredSize(new java.awt.Dimension(80, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        jPanel3.add(texRestante, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel3, gridBagConstraints);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Accept.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(btnAceptar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarTodas;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnQuitarTodas;
    private javax.swing.JComboBox comTipoPlan;
    private javax.swing.JFormattedTextField formatedTotal;
    private javax.swing.JFormattedTextField formatedViviendas;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labNombre;
    private javax.swing.JLabel labNroViviendasPorAño;
    private javax.swing.JLabel labRestante;
    private javax.swing.JLabel labTipoPlan;
    private javax.swing.JLabel labTotal;
    private javax.swing.JSpinner spinAños;
    private javax.swing.JTable tabProvincias;
    private javax.swing.JTable tabProvinciasSeleccionadas;
    private javax.swing.JTextField texNombre;
    private javax.swing.JTextField texRestante;
    private javax.swing.JTextField texTotalViviendas;
    // End of variables declaration//GEN-END:variables

    

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public void setBtnAgregar(JButton btnAgregar) {
        this.btnAgregar = btnAgregar;
    }

    public JButton getBtnAgregarTodas() {
        return btnAgregarTodas;
    }

    public void setBtnAgregarTodas(JButton btnAgregarTodas) {
        this.btnAgregarTodas = btnAgregarTodas;
    }

    public JButton getBtnQuitar() {
        return btnQuitar;
    }

    public void setBtnQuitar(JButton btnQuitar) {
        this.btnQuitar = btnQuitar;
    }

    public JButton getBtnQuitarTodas() {
        return btnQuitarTodas;
    }

    public void setBtnQuitarTodas(JButton btnQuitarTodas) {
        this.btnQuitarTodas = btnQuitarTodas;
    }

    public JComboBox getComTipoPlan() {
        return comTipoPlan;
    }

    public void setComTipoPlan(JComboBox comTipoPlan) {
        this.comTipoPlan = comTipoPlan;
    }

    public JFormattedTextField getFormatedViviendas() {
        return formatedViviendas;
    }

    public void setFormatedViviendas(JFormattedTextField formatedViviendas) {
        this.formatedViviendas = formatedViviendas;
    }

    public JSpinner getSpinAños() {
        return spinAños;
    }

    public void setSpinAños(JSpinner spinAños) {
        this.spinAños = spinAños;
    }

    public JTable getTabProvinciasSeleccionadas() {
        return tabProvinciasSeleccionadas;
    }

    public void setTabProvinciasSeleccionadas(JTable tabProvincias) {
        this.tabProvinciasSeleccionadas = tabProvincias;
    }

    public JTable getTabProvincias() {
        return tabProvincias;
    }

    public void setTabProvincias(JTable tabProvincias) {
        this.tabProvincias = tabProvincias;
    }

    public JTextField getTexNombre() {
        return texNombre;
    }

    public void setTexNombre(JTextField texNombre) {
        this.texNombre = texNombre;
    }

    public JTextField getTexTotalViviendas() {
        return texTotalViviendas;
    }

    public void setTexTotalViviendas(JTextField texTotalViviendas) {
        this.texTotalViviendas = texTotalViviendas;
    }

    public JFormattedTextField getFormatedTotal() {
        return formatedTotal;
    }

    public void setFormatedTotal(JFormattedTextField formatedTotal) {
        this.formatedTotal = formatedTotal;
    }

    public JLabel getLabTotal() {
        return labTotal;
    }

    public void setLabTotal(JLabel labTotal) {
        this.labTotal = labTotal;
    }

    public JLabel getLabRestante() {
        return labRestante;
    }

    public void setLabRestante(JLabel labRestante) {
        this.labRestante = labRestante;
    }

    public JTextField getTexRestante() {
        return texRestante;
    }

    public void setTexRestante(JTextField texRestante) {
        this.texRestante = texRestante;
    }
}
