/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelTablasPlan.java
 *
 * Created on 23/12/2010, 11:29:33
 */

package viviendas.gui.Plan.modificar;

import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author desarrollo
 */
public class PanelTablasPlan extends javax.swing.JPanel {

    /** Creates new form PanelTablasPlan */
    public PanelTablasPlan() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        _contenedor = new javax.swing.JLayeredPane();
        _scrOperatoria = new javax.swing.JScrollPane();
        _tblOperatoria = new javax.swing.JTable();
        _scrSectEconom = new javax.swing.JScrollPane();
        _tblSectorEconomico = new javax.swing.JTable();
        _scrCiudad = new javax.swing.JScrollPane();
        _tblCiudad = new javax.swing.JTable();
        _scrProvincia = new javax.swing.JScrollPane();
        _tblProvincia = new javax.swing.JTable();
        _scrAño = new javax.swing.JScrollPane();
        _tblAños = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        _contenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        _tblOperatoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        _scrOperatoria.setViewportView(_tblOperatoria);

        _scrOperatoria.setBounds(190, 10, 290, 440);
        _contenedor.add(_scrOperatoria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        _tblSectorEconomico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        _scrSectEconom.setViewportView(_tblSectorEconomico);

        _scrSectEconom.setBounds(150, 10, 300, 450);
        _contenedor.add(_scrSectEconom, javax.swing.JLayeredPane.DEFAULT_LAYER);

        _tblCiudad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        _scrCiudad.setViewportView(_tblCiudad);

        _scrCiudad.setBounds(100, 10, 310, 460);
        _contenedor.add(_scrCiudad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        _tblProvincia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        _scrProvincia.setViewportView(_tblProvincia);

        _scrProvincia.setBounds(60, 10, 320, 470);
        _contenedor.add(_scrProvincia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        _tblAños.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        _scrAño.setViewportView(_tblAños);

        _scrAño.setBounds(20, 10, 280, 480);
        _contenedor.add(_scrAño, javax.swing.JLayeredPane.DEFAULT_LAYER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(_contenedor, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane _contenedor;
    private javax.swing.JScrollPane _scrAño;
    private javax.swing.JScrollPane _scrCiudad;
    private javax.swing.JScrollPane _scrOperatoria;
    private javax.swing.JScrollPane _scrProvincia;
    private javax.swing.JScrollPane _scrSectEconom;
    private javax.swing.JTable _tblAños;
    private javax.swing.JTable _tblCiudad;
    private javax.swing.JTable _tblOperatoria;
    private javax.swing.JTable _tblProvincia;
    private javax.swing.JTable _tblSectorEconomico;
    // End of variables declaration//GEN-END:variables

    public JScrollPane getScrAño() {
        return _scrAño;
    }

    public JScrollPane getScrCiudad() {
        return _scrCiudad;
    }

    public JScrollPane getScrOperatoria() {
        return _scrOperatoria;
    }

    public JScrollPane getScrProvincia() {
        return _scrProvincia;
    }

    public JScrollPane getScrSectEconom() {
        return _scrSectEconom;
    }

    public JTable getTblAños() {
        return _tblAños;
    }

    public JTable getTblCiudad() {
        return _tblCiudad;
    }

    public JTable getTblOperatoria() {
        return _tblOperatoria;
    }

    public JTable getTblProvincia() {
        return _tblProvincia;
    }

    public JTable getTblSectorEconomico() {
        return _tblSectorEconomico;
    }

}
