/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUUsuario.java
 *
 * Created on 26/01/2011, 13:45:03
 */

package viviendas.gui.usuario;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author batte
 */
public class IUUsuario extends javax.swing.JInternalFrame {

    /** Creates new form IUUsuario */
    public IUUsuario() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labUsuario = new javax.swing.JLabel();
        _txtUsuario = new javax.swing.JTextField();
        labContraseñaAntigua = new javax.swing.JLabel();
        _txtContrasenia = new javax.swing.JPasswordField();
        _btnAceptar = new javax.swing.JButton();
        _btnCancelar = new javax.swing.JButton();
        labReingreseContraseña = new javax.swing.JLabel();
        _txtReingreseContrasenia = new javax.swing.JPasswordField();
        labContraseñaNueva = new javax.swing.JLabel();
        _txtContraseniaNueva = new javax.swing.JPasswordField();

        setClosable(true);
        setTitle("Usuario");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labUsuario.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 29, 8, 29);
        getContentPane().add(labUsuario, gridBagConstraints);

        _txtUsuario.setText("luis");
        _txtUsuario.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 29, 8, 29);
        getContentPane().add(_txtUsuario, gridBagConstraints);

        labContraseñaAntigua.setText("Contraseña Antigua");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 29, 8, 29);
        getContentPane().add(labContraseñaAntigua, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 29, 8, 29);
        getContentPane().add(_txtContrasenia, gridBagConstraints);

        _btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Accept.png"))); // NOI18N
        _btnAceptar.setText("Aceptar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 29, 8, 29);
        getContentPane().add(_btnAceptar, gridBagConstraints);

        _btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viviendas/imagenes/Log Out_16x16.png"))); // NOI18N
        _btnCancelar.setText("Salir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 29, 8, 29);
        getContentPane().add(_btnCancelar, gridBagConstraints);

        labReingreseContraseña.setText("Reingrese Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 29, 8, 29);
        getContentPane().add(labReingreseContraseña, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 29, 8, 29);
        getContentPane().add(_txtReingreseContrasenia, gridBagConstraints);

        labContraseñaNueva.setText("Contraseña Nueva");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 29, 8, 29);
        getContentPane().add(labContraseñaNueva, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 29, 8, 29);
        getContentPane().add(_txtContraseniaNueva, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnAceptar;
    private javax.swing.JButton _btnCancelar;
    private javax.swing.JPasswordField _txtContrasenia;
    private javax.swing.JPasswordField _txtContraseniaNueva;
    private javax.swing.JPasswordField _txtReingreseContrasenia;
    private javax.swing.JTextField _txtUsuario;
    private javax.swing.JLabel labContraseñaAntigua;
    private javax.swing.JLabel labContraseñaNueva;
    private javax.swing.JLabel labReingreseContraseña;
    private javax.swing.JLabel labUsuario;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAceptar() {
        return _btnAceptar;
    }

    public void setBtnAceptar(JButton _btnAceptar) {
        this._btnAceptar = _btnAceptar;
    }

    public JButton getBtnCancelar() {
        return _btnCancelar;
    }

    public void setBtnCancelar(JButton _btnCancelar) {
        this._btnCancelar = _btnCancelar;
    }

    public JPasswordField getTxtContrasenia() {
        return _txtContrasenia;
    }

    public void setTxtContrasenia(JPasswordField _txtContrasenia) {
        this._txtContrasenia = _txtContrasenia;
    }

    public JPasswordField getTxtContraseniaNueva() {
        return _txtContraseniaNueva;
    }

    public void setTxtContraseniaNueva(JPasswordField _txtContraseniaNueva) {
        this._txtContraseniaNueva = _txtContraseniaNueva;
    }

    public JPasswordField getTxtReingreseContrasenia() {
        return _txtReingreseContrasenia;
    }

    public void setTxtReingreseContrasenia(JPasswordField _txtReingreseContrasenia) {
        this._txtReingreseContrasenia = _txtReingreseContrasenia;
    }

    public JTextField getTxtUsuario() {
        return _txtUsuario;
    }

    public void setTxtUsuario(JTextField _txtUsuario) {
        this._txtUsuario = _txtUsuario;
    }
}
